name: Push components to Espressif Component Service

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: >
            t9602;mc3479;
          namespace: "pedrominatel"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
